name: Add Subscribers
on:
  issues:
    types: [opened, labeled, unlabeled]

jobs:
  add_subscribers:
    runs-on: ubunutu-latest
    name: CC folks
    steps:
      - uses: zpao/manage-issue-subscribers@master
        with:
          repo-token: '{{ secrets.GITHUB_TOKEN }}'
